name: Merge AdBlock Lists

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  merge-lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run merge script
        run: python rules/scripts/merge_blocklists.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'bot: 更新拦截规则列表'
          branch: 'master'
